FROM golang:1.20.1 as build
WORKDIR /app

COPY ["go.mod", "go.sum", "./"]

RUN go mod download

COPY . .

RUN go build -o ./coredns

FROM gcr.io/distroless/base-debian11:latest

COPY --from=build /app/coredns /

EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]